/**
 * Minimal, dependency-free className utility.
 *
 * `cn()` does two things:
 *   1. Flattens strings / arrays / objects into a single class string (clsx-like).
 *   2. Resolves conflicting Tailwind utilities by keeping the *last* one.
 *
 * The conflict resolution is intentionally narrow: it only knows about a
 * curated list of Tailwind group prefixes. Anything it does not recognise is
 * always kept, which is the safe behaviour (an unknown utility is far more
 * likely to be an addition than a conflict).
 *
 * Component APIs are designed so `className` is appended last, which means a
 * caller's override always wins over a component's default.
 */

export type ClassValue =
  | string
  | number
  | null
  | undefined
  | false
  | ClassValue[]
  | { [key: string]: boolean | null | undefined };

function flatten(value: ClassValue, out: string[]): void {
  if (!value && value !== 0) return;

  if (typeof value === "string" || typeof value === "number") {
    for (const token of String(value).split(/\s+/)) {
      if (token) out.push(token);
    }
    return;
  }

  if (Array.isArray(value)) {
    for (const item of value) flatten(item, out);
    return;
  }

  if (typeof value === "object") {
    for (const [key, enabled] of Object.entries(value)) {
      if (enabled) flatten(key, out);
    }
  }
}

/**
 * Tailwind group prefixes. The longest matching prefix wins, so `px-4` resolves
 * to the `px` group rather than the `p` group.
 */
const GROUPS = [
  // layout
  "p", "px", "py", "pt", "pr", "pb", "pl",
  "m", "mx", "my", "mt", "mr", "mb", "ml",
  "gap", "gap-x", "gap-y", "space-x", "space-y",
  "size", "w", "h", "min-w", "min-h", "max-w", "max-h",
  "basis", "aspect", "inset", "top", "right", "bottom", "left",
  "z", "order", "col-span", "col-start", "col-end", "row-span",
  // flex / grid alignment
  "flex", "grid", "inline-flex",
  "items", "justify", "self", "place-content", "place-items", "content",
  // typography
  "font", "font-stretch", "leading", "tracking", "text-align",
  "whitespace", "truncate", "indent", "vertical-align", "list-style",
  // colour
  "text-color", "bg", "from", "via", "to", "fill", "stroke",
  "border", "border-x", "border-y", "border-t", "border-r", "border-b",
  "border-l", "border-w", "border-c",
  "outline", "ring", "shadow", "divide",
  // effects + motion
  "opacity", "blur", "backdrop-blur", "transition", "duration", "delay",
  "ease", "animate", "overflow", "overflow-x", "overflow-y", "object",
  "aspect-ratio",
] as const;

/**
 * Tailwind overloads the `text-` prefix across four different CSS properties,
 * so each one needs to be told apart or unrelated utilities will cancel each
 * other out (`text-display-xl` and `text-left` are not a conflict).
 */

/** The Material type scale, plus Tailwind's own size scale. */
const TEXT_SIZE_VALUES = new Set([
  "xs", "sm", "base", "lg", "xl", "2xl", "3xl", "4xl", "5xl", "6xl", "7xl",
  "8xl", "9xl",
]);

/** Families generated by this project's `--text-*` theme tokens. */
const TEXT_SIZE_PREFIXES = [
  "display-",
  "headline-",
  "title-",
  "body-",
  "label-",
  "metric",
];

const TEXT_ALIGN_VALUES = new Set([
  "left", "center", "right", "justify", "start", "end",
]);

const TEXT_WRAP_VALUES = new Set(["wrap", "nowrap", "balance", "pretty"]);

const TEXT_DECORATION_VALUES = new Set([
  "underline", "overline", "line-through", "no-underline",
]);

const TEXT_TRANSFORM_VALUES = new Set([
  "uppercase", "lowercase", "capitalize", "normal",
]);

/**
 * Arbitrary values need a heuristic: `text-[3rem]` is a size, while
 * `text-[#fff]`, `text-[var(--x)]` and `text-[color:...]` are colours.
 */
function isArbitraryColour(value: string): boolean {
  const inner = value.slice(1, value.lastIndexOf("]"));
  return (
    inner.startsWith("#") ||
    /^(rgb|rgba|hsl|hsla|oklch|oklab|lab|lch|color|color-mix)\(/.test(inner)
  );
}

function textGroup(value: string): string {
  if (value.startsWith("[")) {
    return isArbitraryColour(value) ? "text-color" : "text-size";
  }
  if (TEXT_SIZE_VALUES.has(value)) return "text-size";
  if (TEXT_SIZE_PREFIXES.some((prefix) => value === prefix || value.startsWith(prefix))) {
    return "text-size";
  }
  if (TEXT_ALIGN_VALUES.has(value)) return "text-align";
  if (TEXT_WRAP_VALUES.has(value)) return "text-wrap";
  if (TEXT_DECORATION_VALUES.has(value)) return "text-decoration";
  if (TEXT_TRANSFORM_VALUES.has(value)) return "text-transform";
  return "text-color";
}


/** Groups that collapse onto another group so overrides behave as expected. */
const ALIASES: Record<string, string> = {
  "border-w": "border",
  "border-c": "border",
  "font-stretch": "font",
  "aspect-ratio": "aspect",
};

function matchPrefix(base: string): string | null {
  let best: string | null = null;
  for (const prefix of GROUPS) {
    if (base === prefix || base.startsWith(`${prefix}-`)) {
      if (best === null || prefix.length > best.length) best = prefix;
    }
  }
  return best;
}

/**
 * `display` utilities all share one group, so `flex` and `grid` conflict even
 * though neither is a prefix of the other.
 */
const DISPLAY_VALUES = new Set([
  "block", "inline-block", "inline", "flex", "inline-flex", "grid",
  "inline-grid", "contents", "table", "inline-table", "list-item",
  "flow-root", "hidden",
]);

function groupOf(className: string): string | null {
  // Split off variant prefixes (`md:hover:`) and any leading negative sign.
  const lastColon = className.lastIndexOf(":");
  const variant = lastColon === -1 ? "" : className.slice(0, lastColon + 1);
  let base = lastColon === -1 ? className : className.slice(lastColon + 1);

  // A leading `-` is a modifier, not part of the group: `-mt-4` replaces `mt-2`.
  if (base.startsWith("-")) base = base.slice(1);

  if (DISPLAY_VALUES.has(base)) return `${variant}display`;

  // Radius utilities: `rounded-3xl` is the base group, while each edge
  // (`rounded-t-lg`, `rounded-b-lg`, ...) is its own group so that setting
  // different corners composes instead of overwriting.
  if (base === "rounded" || base.startsWith("rounded-")) {
    const rest = base.slice("rounded".length).replace(/^-/, "");
    const edge = /^(t|b|l|r|tl|tr|bl|br)(-|$)/.exec(rest);
    return `${variant}rounded${edge ? `-${edge[1]}` : ""}`;
  }

  // `text-lg` is a size; `text-red-500` is a colour; `text-left` is neither.
  // This is checked before the arbitrary-value branch below because
  // `text-[...]` can be a size *or* a colour, and only this branch can tell.
  if (base.startsWith("text-")) {
    return `${variant}${textGroup(base.slice("text-".length))}`;
  }

  // Arbitrary values: `w-[calc(100%-2rem)]` -> group `w`.
  if (base.includes("[")) {
    const head = base.slice(0, base.indexOf("[")).replace(/-$/, "");
    const matched = matchPrefix(head);
    return matched ? `${variant}${ALIASES[matched] ?? matched}` : null;
  }

  const matched = matchPrefix(base);
  return matched ? `${variant}${ALIASES[matched] ?? matched}` : null;
}

function merge(classes: string[]): string {
  const resolved: string[] = [];
  const lastIndexByGroup = new Map<string, number>();

  for (const className of classes) {
    const group = groupOf(className);
    if (group === null) {
      resolved.push(className);
      continue;
    }
    const previous = lastIndexByGroup.get(group);
    if (previous !== undefined) resolved[previous] = "";
    lastIndexByGroup.set(group, resolved.length);
    resolved.push(className);
  }

  return resolved.filter(Boolean).join(" ");
}

/** Join conditional class values and drop conflicting Tailwind utilities. */
export function cn(...inputs: ClassValue[]): string {
  const flat: string[] = [];
  for (const input of inputs) flatten(input, flat);
  return merge(flat);
}
