import { ACCENT_PRESETS, type AccentPreset } from "./accents";
import { createAccentTheme, COLOR_ROLES } from "./theme";
import { DURATION, EASING, SHAPE_SCALE, TYPE_SCALE } from "./tokens";

/**
 * Serialise the design tokens into a CSS string.
 *
 * This is the bridge between the TypeScript token definitions and the
 * stylesheet. The root layout renders it into a `<style>` element, so the
 * server ships every accent, in both schemes, as plain CSS.
 *
 * The payoff is that theming costs nothing at runtime: switching light/dark or
 * accent only flips attributes on `<html>`, and CSS does the rest. No colour
 * maths and no token objects are ever shipped to the browser.
 */

/** Colour custom properties for one scheme, e.g. `--md-light-primary`. */
function schemeDeclarations(preset: AccentPreset, selector: string): string {
  const theme = createAccentTheme(preset);
  const lines = [
    ...COLOR_ROLES.map((role) => `  --md-light-${role}: ${theme.light[role]};`),
    ...COLOR_ROLES.map((role) => `  --md-dark-${role}: ${theme.dark[role]};`),
  ];
  return `${selector} {\n${lines.join("\n")}\n}`;
}

/**
 * Map each scheme onto the scheme-agnostic `--md-sys-color-*` aliases. A
 * single `.dark` class on the root element then swaps the whole UI.
 */
function aliasBlock(): string {
  const light = COLOR_ROLES.map((role) => `  --md-sys-color-${role}: var(--md-light-${role});`);
  const dark = COLOR_ROLES.map((role) => `  --md-sys-color-${role}: var(--md-dark-${role});`);
  return [`html {\n${light.join("\n")}\n}`, `html.dark {\n${dark.join("\n")}\n}`].join("\n\n");
}

function shapeBlock(): string {
  const lines = Object.entries(SHAPE_SCALE).map(([key, value]) => `  --md-shape-${key}: ${value};`);
  return `html {\n${lines.join("\n")}\n}`;
}

/**
 * Each type style is emitted as a CSS `font` shorthand. That lets a single
 * Tailwind `--text-*` declaration carry size, line height, tracking and weight
 * together, exactly as the Material scale defines them.
 */
function typeBlock(): string {
  const lines = Object.entries(TYPE_SCALE).map(([key, style]) => {
    const shorthand = [
      style.fontWeight,
      style.fontSize,
      `/${style.lineHeight}`,
      style.letterSpacing,
      "var(--font-sans)",
    ].join(" ");
    return `  --md-type-${key}: ${shorthand};`;
  });
  return `html {\n${lines.join("\n")}\n}`;
}

function motionBlock(): string {
  const lines = [
    ...Object.entries(EASING).map(([key, value]) => `  --md-ease-${key}: ${value};`),
    ...Object.entries(DURATION).map(([key, value]) => `  --md-duration-${key}: ${value};`),
  ];
  return `html {\n${lines.join("\n")}\n}`;
}

/**
 * Shadow values differ between schemes: light surfaces want a soft neutral
 * shadow, dark surfaces want a deeper, cooler one to separate from the
 * background at all.
 */
const ELEVATION_LIGHT: Record<number, string> = {
  1: "0 1px 2px 0 rgb(0 0 0 / 0.16), 0 1px 3px 1px rgb(0 0 0 / 0.08)",
  2: "0 1px 2px 0 rgb(0 0 0 / 0.16), 0 2px 6px 2px rgb(0 0 0 / 0.08)",
  3: "0 1px 3px 0 rgb(0 0 0 / 0.14), 0 4px 8px 3px rgb(0 0 0 / 0.08)",
  4: "0 2px 3px 0 rgb(0 0 0 / 0.14), 0 6px 10px 4px rgb(0 0 0 / 0.08)",
  5: "0 4px 4px 0 rgb(0 0 0 / 0.12), 0 8px 12px 6px rgb(0 0 0 / 0.08)",
};

const ELEVATION_DARK: Record<number, string> = {
  1: "0 1px 2px 0 rgb(0 0 0 / 0.4), 0 1px 3px 1px rgb(0 0 0 / 0.24)",
  2: "0 1px 2px 0 rgb(0 0 0 / 0.4), 0 2px 6px 2px rgb(0 0 0 / 0.26)",
  3: "0 1px 3px 0 rgb(0 0 0 / 0.36), 0 4px 8px 3px rgb(0 0 0 / 0.26)",
  4: "0 2px 3px 0 rgb(0 0 0 / 0.36), 0 6px 10px 4px rgb(0 0 0 / 0.26)",
  5: "0 4px 4px 0 rgb(0 0 0 / 0.34), 0 8px 12px 6px rgb(0 0 0 / 0.28)",
};

function elevationBlock(): string {
  const light = Object.entries(ELEVATION_LIGHT).map(([key, value]) => `  --md-elev-${key}: ${value};`);
  const dark = Object.entries(ELEVATION_DARK).map(([key, value]) => `  --md-elev-${key}: ${value};`);
  return [`html {\n${light.join("\n")}\n}`, `html.dark {\n${dark.join("\n")}\n}`].join("\n\n");
}

/** Build the complete token stylesheet covering every accent preset. */
export function themeCss(): string {
  const [fallback, ...accents] = ACCENT_PRESETS;

  const blocks = [
    "/* Generated by src/lib/material/css.ts - do not edit by hand. */",
    // The first preset doubles as the no-attribute fallback, so the page still
    // renders correctly if JavaScript never runs.
    schemeDeclarations(fallback, ":root"),
    // `html[data-accent]` (0,1,1) outranks `:root` (0,1,0), so these win
    // regardless of source order.
    ...accents.map((preset) =>
      schemeDeclarations(preset, `html[data-accent="${preset.id}"]`),
    ),
    aliasBlock(),
    shapeBlock(),
    typeBlock(),
    motionBlock(),
    elevationBlock(),
  ];

  return blocks.join("\n\n");
}

